CREATE TABLE combos (
  id        INT AUTO_INCREMENT PRIMARY KEY,
  nome      VARCHAR(200) NOT NULL,
  descricao TEXT,
  preco     DECIMAL(10,2) NOT NULL,
  imagem    VARCHAR(500) DEFAULT NULL,
  ativo     TINYINT NOT NULL DEFAULT 1,
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE combo_itens (
  id         INT AUTO_INCREMENT PRIMARY KEY,
  combo_id   INT NOT NULL,
  produto_id INT NOT NULL,
  quantidade INT NOT NULL DEFAULT 1,
  FOREIGN KEY (combo_id)   REFERENCES combos(id) ON DELETE CASCADE,
  FOREIGN KEY (produto_id) REFERENCES produtos(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
